datatypes-one:
	mkdir -p contracts
	cp ../src/contracts/DataTypes.sol contracts/
	npx hardhat test test_dataTypes.js --grep 'step 1'

datatypes-two:
	mkdir -p contracts
	cp ../src/contracts/DataTypes.sol contracts/
	npx hardhat test test_dataTypes.js --grep 'step 2'

datatypes-three:
	mkdir -p contracts
	cp ../src/contracts/DataTypes.sol contracts/
	npx hardhat test test_dataTypes.js --grep 'step 3'